insert into public.macokasa_records (collection, payload) values
('operators', '{
  "id": "op-seed-001",
  "membershipNumber": "MCK-LL-2026-9001",
  "fullName": "Seed Operator",
  "phone": "+265 999 000 001",
  "email": "seed.operator@example.com",
  "nationalId": "MW-SEED-001",
  "operatorCategory": "Motorcycle operator",
  "district": "Lilongwe",
  "sex": "Male",
  "operatingArea": "Lilongwe Review Rank",
  "membershipPlan": "regular",
  "membershipType": "operator",
  "expiresOn": "2026-12-31",
  "hasLicense": false,
  "licenseNumber": "",
  "ownershipStatus": "Rents motorcycle",
  "motorcycleId": "",
  "helmetUse": true,
  "passengerHelmet": false,
  "licensePlate": "LL DEMO",
  "trackerInstalled": false,
  "status": "training due",
  "createdAt": "2026-06-24"
}'::jsonb),
('stories', '{
  "id": "story-seed-001",
  "title": "Road safety practice strengthens Kabaza verification",
  "category": "Training",
  "summary": "MACOKASA and safety stakeholders are building a verified, safer Kabaza sector through training, membership, and digital card authentication.",
  "body": "This seeded story appears on the public website and can be replaced by webpage admin posts with uploaded visuals.",
  "imageData": "./assets/macokasa-road-safety-training.jpg",
  "status": "published",
  "createdAt": "2026-06-24"
}'::jsonb);
