insert into public.macokasa_records (collection, payload) values
('operators', '{
  "id": "op-seed-001",
  "membershipNumber": "MCK-LL-2026-9001",
  "fullName": "Seed Operator",
  "phone": "+265 999 000 001",
  "email": "seed.operator@example.com",
  "nationalId": "MW-SEED-001",
  "operatorCategory": "Motorcycle operator",
  "district": "Lilongwe",
  "sex": "Male",
  "operatingArea": "Lilongwe Review Rank",
  "membershipPlan": "regular",
  "membershipType": "operator",
  "expiresOn": "2026-12-31",
  "hasLicense": false,
  "licenseNumber": "",
  "ownershipStatus": "Rents motorcycle",
  "motorcycleId": "",
  "helmetUse": true,
  "passengerHelmet": false,
  "licensePlate": "LL DEMO",
  "trackerInstalled": false,
  "status": "training due",
  "createdAt": "2026-06-24"
}'::jsonb),
('stories', '{
  "id": "story-seed-001",
  "title": "ROSAF partnership links membership to practical rider training",
  "category": "Training",
  "location": "Lilongwe",
  "partners": ["ROSAF", "MACOKASA"],
  "impactLine": "Membership becomes a pathway to practical skills, refresher learning, and support towards formal licensing.",
  "summary": "Through ROSAF, registered members can access reduced-fee training support that turns road-safety messages into supervised riding practice.",
  "body": "MACOKASA links registered members who need instruction or refresher support to the ROSAF training pathway. The shared record helps the coalition recognise progress and identify where more support is needed.",
  "images": ["./assets/rosaf-road-safety-practical.jpg", "./assets/kabaza-safety-mobilisation.jpg"],
  "imageData": "./assets/rosaf-road-safety-practical.jpg",
  "status": "published",
  "createdAt": "2026-07-19"
}'::jsonb);
