import { copyFileSync, mkdirSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { resolve, join } from "node:path";

/**
 * Writes public/config.js and copies src/ into public/src/.
 *
 * SECURITY: everything written to config.js is publicly readable at
 * https://<site>/config.js. Only values safe to publish belong here.
 * The Supabase anon key is designed to be public and is protected by
 * row level security — it grants nothing on its own.
 *
 * Never add: service role keys, portal passwords, API secrets, SMTP
 * credentials, SMS or payment provider tokens.
 */

const forbidden = [
  "SUPABASE_SERVICE_ROLE_KEY",
  "MACOKASA_STAFF_PASSWORD",
  "MACOKASA_OWNER_PASSWORD",
  "MACOKASA_PRINT_PASSWORD",
  "MACOKASA_WEBADMIN_PASSWORD",
  "PAYCHANGU_SECRET_KEY",
  "PAYCHANGU_WEBHOOK_SECRET"
];

const leaked = forbidden.filter((k) => process.env[k]);
if (leaked.length) {
  console.warn(
    `\n[write-config] WARNING: ${leaked.join(", ")} present in the environment.\n` +
      "  These are NOT written to the client bundle and must not be set on a\n" +
      "  static site. Remove them from the deploy environment.\n"
  );
}

const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || "";

const config = {
  supabaseUrl,
  supabaseAnonKey,
  publicBaseUrl: process.env.PUBLIC_BASE_URL || "__origin__",
  buildTime: new Date().toISOString()
};

const banner = `/* Generated by scripts/write-config.mjs. Do not edit.
   This file is PUBLIC. Never add secrets here. */\n`;

writeFileSync(resolve("public", "config.js"), `${banner}window.MACOKASA_CONFIG = ${JSON.stringify(config, null, 2)};\n`);

/** Recursively copy src/ so the module tree is preserved. */
function copyTree(from, to) {
  mkdirSync(to, { recursive: true });
  for (const entry of readdirSync(from)) {
    const src = join(from, entry);
    const dest = join(to, entry);
    if (statSync(src).isDirectory()) copyTree(src, dest);
    else copyFileSync(src, dest);
  }
}

copyTree(resolve("src"), resolve("public", "src"));

console.log(
  `[write-config] public/config.js written — ${
    supabaseUrl && supabaseAnonKey ? "LIVE Supabase" : "NO database configured"
  }.`
);
