import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Writes public/config.js.
 *
 * SECURITY: everything written here is publicly readable by any visitor
 * at https://<site>/config.js. Only ever put values here that are safe
 * to publish. The Supabase anon key is designed to be public and is
 * protected by row level security — it is NOT a secret in the sense of
 * granting access on its own.
 *
 * Never add: service role keys, portal passwords, API secrets, SMTP
 * credentials, or SMS/WhatsApp provider tokens.
 */

const forbidden = [
  "SUPABASE_SERVICE_ROLE_KEY",
  "MACOKASA_STAFF_PASSWORD",
  "MACOKASA_OWNER_PASSWORD",
  "MACOKASA_PRINT_PASSWORD",
  "MACOKASA_WEBADMIN_PASSWORD"
];

const leaked = forbidden.filter((key) => process.env[key]);
if (leaked.length) {
  console.warn(
    `\n[write-config] WARNING: ${leaked.join(", ")} is set in the environment.\n` +
      "  These are legacy prototype variables and are NOT written to the client\n" +
      "  bundle. Portal access now uses Supabase Auth. Remove them from Render.\n"
  );
}

const supabaseUrl = process.env.SUPABASE_URL || "";
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || "";

const config = {
  supabaseUrl,
  supabaseAnonKey,
  useDemoData: !supabaseUrl || !supabaseAnonKey,
  publicBaseUrl: process.env.PUBLIC_BASE_URL || "__origin__",
  organisation: {
    name: process.env.MACOKASA_ORG_NAME || "MACOKASA",
    email: process.env.MACOKASA_CONTACT_EMAIL || "",
    phone: process.env.MACOKASA_CONTACT_PHONE || "",
    address: process.env.MACOKASA_CONTACT_ADDRESS || "",
    safetyLine: process.env.MACOKASA_SAFETY_LINE || ""
  },
  buildTime: new Date().toISOString()
};

const banner = `/* Generated by scripts/write-config.mjs. Do not edit by hand.
   This file is PUBLIC. Never add secrets here. */\n`;

const output = `${banner}window.MACOKASA_CONFIG = ${JSON.stringify(config, null, 2)};\n`;
writeFileSync(resolve("public", "config.js"), output);

mkdirSync(resolve("public", "src"), { recursive: true });
for (const file of ["app.js", "data.js", "styles.css"]) {
  copyFileSync(resolve("src", file), resolve("public", "src", file));
}

console.log(
  `[write-config] Wrote public/config.js — ${config.useDemoData ? "DEMO data (no Supabase configured)" : "LIVE Supabase"}.`
);
